/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Common constants for common component.
 */
export class Constants {

  // space
  static readonly SM_SPACE: number = 5;
  static readonly MD_SPACE: number = 10;
  static readonly LG_SPACE: number = 15;

  // blur scale
  static readonly BLUR_SCALE: number = 0.15;

  // opacity
  static readonly SECOND_LEVEL_OPACITY: number = 0.6;
}