/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const TagColorMap: Map<string, string> = new Map<string, string>([
  ['开发者故事', '65BB5C'],
  ['活动公告', 'FF3E50'],
  ['精彩活动', 'FF3E50'],
  ['技术干货', '0A59F7'],
  ['鸿蒙生态', '0A59F7']
]);
